### PR TITLE
added instructions to get dependencies and run project to readme

### PR DESCRIPTION
**Pull request by Sohaib-50**
I have added to the readme file instructions for downloading dependencies and running the flutter app that would be useful for other contributed or people just looking to run the app on their own computer.

### CODE REVIEW

**Comment by cynthiakonar** [comment]
> I have added to the readme file instructions for downloading dependencies and running the flutter app that would be useful for other contributed or people just looking to run the app on their own computer.

The changes are not visible in readme, can you please check ?

**Comment by Sohaib-50** [comment]
> > I have added to the readme file instructions for downloading dependencies and running the flutter app that would be useful for other contributed or people just looking to run the app on their own computer.
> 
> The changes are not visible in readme, can you please check ?

Lmao OMG I didn't save the file before pushing sorry! 😅
I'll do that now.

**Comment by cynthiakonar** [comment]
Can you add the app screenshots as well?

**Comment by Sohaib-50** [comment]
> Can you add the app screenshots as well?

About that, I've dmd you on discord. There's an issue with running the app

**Comment by cynthiakonar** [comment]
> About that, I've dmd you on discord. There's an issue with running the app

Yes I got the issue, I will merge your changes. Thank you~

**Pull request merged**
